import { SettingsProvider } from "@/context/SettingsContext";
import { TimerProvider } from "@/context/TimerContext";
import "@/styles/main.css"
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="pl">
      <body>
        <SettingsProvider>
          <Toaster position="top-right" />
          <TimerProvider>
          {children}
          </TimerProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}