import { SettingsProvider } from "@/context/SettingsContext";
import { TimerProvider } from "@/context/TimerContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="pl">
      <body>
        <SettingsProvider>
          <TimerProvider>
          {children}
          </TimerProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}